name: workhub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  video_player: ^2.6.0
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/aaa.jpg
    - assets/images/web.png
    - assets/images/mobile.png
    - assets/images/ecommerce.png
    - assets/images/design.png
    - assets/gifs/demo.gif
    - assets/videos/demo.mp4
